# Generated by Django 4.2.2 on 2023-10-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('flag', models.ImageField(blank=True, upload_to='flags/%Y/%m/%d/')),
                ('top_beer', models.ImageField(blank=True, upload_to='labels/%Y/%m/%d/')),
                ('content', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
